INSERT INTO MANCARE (nume)
VALUES ('Bobite');
INSERT INTO MANCARE (nume)
VALUES ('Conserva');
INSERT INTO MANCARE (nume)
VALUES ('Paine');


INSERT INTO ANGAJAT (ID, CNP, NUME, PRENUME, PASSWORD, ROLE, USERNAME)
VALUES (1, '1234567890123', 'Doe', 'John', '$2a$12$dpoY3uHTXKkZj1r3HY3V4eve8jWXSWvesDAeT8y/dpf9ICyyz8deS', 'ADMIN',
        'admin');
